class helping:
  def menu():
      print ("---------------------------------------------------------------")
      print ('Lemonade Stand: cost $500 but you add $100 to your revenue, to buy answer ls.\n')
      print ('Lawn Mower: cost $1100 but you add $250 to your revenue, to buy answer lm.\n')
      print ('Restaurant: cost $2400 but you add $650 to your revenue, to buy answer rs.\n')
      print ('Surf Shop: cost $5300 but you add $1600 to your revenue, to buy answer ss\n')
      print ('House Rental: cost $19000 but you add $4000 to your revenue, to buy answer cr\n')
      print ('Coffee Roaster: cost $41000 but you add  $10000 to your revenue, to buy answer hr.\n')
      print ('You can double the profits of a certain company for a hefty price.\n')
      print ('To double the profits of your Lemonade stand it cost $2000 to buy answer ls2\n')
      print ('To double the profits of your Lawn Mower it cost $5000 to buy answer lm2\n')
      print ('To double the profits of your Restaurant it cost $12500 to buy answer rs2\n')
      print ('To double the profits of your Surf Shop it cost $32000 to buy answer ss2\n')
      print ('To double the profits of your House Renting it cost $80000 to buy answer hr2\n')
      print ('To double the profits of your Coffee Roaster it cost $176000 to buy answer cr2\n')
      print ('To buy all of one thing put an a after the   thing you are going to buy.\n')
      print ('Example: lsa or rsa')
      print ("---------------------------------------------------------------")